import { z } from 'zod';

export const ApprovalLevelSchema = z.enum(['auto', 'notify', 'require']);

export const MurphConfigSchema = z.object({
  agent: z.object({
    name: z.string().default('Murph'),
    model: z.string().default('sonnet'),
    max_budget_per_message_usd: z.number().default(0.50),
    timezone: z.string().default('America/Denver'),
    web_search: z.boolean().default(true),
    api_port: z.number().default(3140),
    welcome_quotes: z.array(z.string()).default([
      'Do not go gentle into that good night.',
      'We used to look up at the sky and wonder at our place in the stars, now we just look down and worry about our place in the dirt.',
      'Mankind was born on Earth. It was never meant to die here.',
      "Love is the one thing we're capable of perceiving that transcends dimensions of time and space.",
      "We've always defined ourselves by the ability to overcome the impossible.",
      "Murphy's law doesn't mean that something bad will happen. It means that whatever can happen, will happen.",
      "I'm not afraid of death. I'm an old physicist. I'm afraid of time.",
      "Maybe we've spent too long trying to figure all this out with theory.",
      "This world's a treasure, but it's been telling us to leave for a while now.",
      '"It\'s not possible." "No. It\'s necessary."',
      "Newton's third law. You've got to leave something behind.",
      "Once you're a parent, you're the ghost of your children's future.",
      'We must reach far beyond our own lifespans. We must think not as individuals but as a species.',
      'Our survival instinct is our single greatest source of inspiration.',
      "Time is relative, okay? It can stretch and it can squeeze, but it can't run backwards.",
      'Accident is the first building block of evolution.',
      "Love isn't something that we invented. It's observable, powerful.",
      "We're still pioneers, we barely begun. Our greatest accomplishments cannot be behind us, cause our destiny lies above us.",
      "We'll find a way, Professor. We always have.",
      "Mankind's next step will be our greatest.",
      "Don't trust the right thing done for the wrong reason. The why of the thing, that's the foundation.",
      "You said science was about admitting what we don't know.",
      "We didn't run out of television screens and planes. We ran out of food.",
      'You might have to decide between seeing your children again and the future of the human race.',
      'We must confront the reality that nothing in our solar system can help us.',
      "We're not meant to save the world. We're meant to leave it.",
      "Don't judge me, Cooper. You were never tested like I was. Few men have been.",
      "Absolute honesty isn't always the most diplomatic nor the safest form of communication with emotional beings.",
      'He knew how hard it would be to get people to work together to save the species instead of themselves.',
      "I don't care much for this pretending. We're back where we started. I want to know where we are. Where we're going.",
      'Let me go home.',
      "There are some things that aren't meant to be known.",
      "A machine doesn't improvise well because you cannot program a fear of death.",
      "I stopped believing you were coming back. Something seemed wrong about dreaming my life away.",
      'When I was a kid, it seemed like they made something new every day.',
      "She's out there. Setting up camp. Alone, in a strange galaxy. Perhaps right now she's settling in for the long nap.",
      'Rage, rage against the dying of the light.',
      'Every hour we spend on that planet will be seven years back on Earth.',
      "Those aren't mountains. They're waves.",
      "Today is my birthday. And it's a special one because you once told me that when you came back, we might be the same age.",
      "I have a cue light I can use to show you when I'm joking, if you like.",
      "Parents are the ghosts of their children's future. I can't be your ghost anymore, Murph.",
      'Cooper, this is no time for caution.',
      "You have Murphy's fire, Amelia.",
      'The only thing that can move across dimensions like time is gravity.',
      'We are the future.',
      'Step out of the shadow. Find something new to orbit.',
      "It's like we've forgotten who we are. Explorers, pioneers, not caretakers.",
      "Nature can't be evil. Nature is formidable but it isn't evil.",
      "That's what I love. You say science is about admitting what we don't know.",
    ]),
  }),
  database: z.object({
    url: z.string().default('postgresql://localhost:5432/murph'),
  }),
  embedding: z.object({
    provider: z.string().default('ollama'),
    model: z.string().default('nomic-embed-text'),
    ollama_url: z.string().default('http://localhost:11434'),
  }),
  security: z.object({
    dashboard_port: z.number().default(3141),
    approval_defaults: z.record(ApprovalLevelSchema).default({
      'gmail.send': 'require',
      'gmail.read': 'auto',
      'imessage.send': 'require',
      'telegram.send': 'notify',
      'bop.*': 'require',
      'mcp.*': 'require',
      'mcp.google.gmail.users.messages.send': 'require',
      'mcp.google.gmail.users.drafts.send': 'require',
      'mcp.google.send_email': 'require',
      'mcp.google.create_draft': 'require',
      'mcp.google.calendar.events.insert': 'notify',
      'mcp.google.calendar.events.delete': 'require',
      'mcp.google.create_event': 'notify',
      'mcp.google.delete_event': 'require',
      'mcp.google.drive.files.delete': 'require',
      'mcp.google.drive.files.create': 'notify',
      'mcp.google.delete_drive_file': 'require',
      'mcp.google.upload_drive_file': 'notify',
      'playwright.*': 'notify',
      'cloudflare.deploy': 'require',
      'creator.*': 'require',
      'scheduler.create': 'notify',
      'hubspot.*': 'notify',
      'gohighlevel.*': 'notify',
      'knowledge.ingest': 'auto',
      'knowledge.delete': 'require',
      'email-maintenance.run': 'auto',
      'email-maintenance.mark_read': 'notify',
      'email-maintenance.archive': 'notify',
      'email-maintenance.apply_label': 'auto',
      'email-maintenance.create_task': 'notify',
      'email-maintenance.reply': 'require',
      'email-maintenance.forward': 'notify',
    }),
  }),
  channels: z.object({
    imessage: z.object({
      enabled: z.boolean().default(false),
      poll_interval_ms: z.number().default(1000),
      chat_db_path: z.string().default('~/Library/Messages/chat.db'),
      allowed_senders: z.array(z.string()).default([]),
    }).default({}),
    telegram: z.object({
      enabled: z.boolean().default(false),
      bot_token: z.string().default(''),
      allowed_user_ids: z.array(z.number()).default([]),
    }).default({}),
  }).default({}),
  knowledge: z.object({
    sources: z.object({
      obsidian: z.object({
        enabled: z.boolean().default(false),
        vault_path: z.string().default(''),
        watch: z.boolean().default(true),
      }).default({}),
      granola: z.object({
        enabled: z.boolean().default(false),
      }).default({}),
      plaud: z.object({
        enabled: z.boolean().default(false),
      }).default({}),
    }).default({}),
  }).default({}),
  mcp_servers: z.array(z.object({
    name: z.string(),
    transport: z.enum(['stdio', 'http']),
    url: z.string().optional(),
    command: z.string().optional(),
    args: z.array(z.string()).optional(),
    headers: z.record(z.string()).optional(),
    env: z.record(z.string()).optional(),
  })).default([]),
  integrations: z.record(z.object({
    enabled: z.boolean(),
  }).passthrough()).default({}),
  creator: z.object({
    enabled: z.boolean().default(false),
    deploy_target: z.string().default('cloudflare'),
    project_prefix: z.string().default('murph-gen'),
  }).default({}),
  scheduler: z.object({
    enabled: z.boolean().default(true),
  }).default({}),
  email_maintenance: z.object({
    enabled: z.boolean().default(false),

    // Core
    goal: z.string().default(''),
    model: z.enum(['haiku', 'sonnet', 'opus']).default('haiku'),
    cadence: z.enum(['15m', '30m', '1h', '6h', 'daily']).default('1h'),
    next_steps: z.string().default(''),

    // Email Scanning
    gmail_query: z.string().default(''),
    lookback_window: z.enum(['1h', '6h', '24h', '3d', '7d']).default('24h'),
    max_emails_per_run: z.number().min(1).max(200).default(50),
    only_unread: z.boolean().default(true),
    scan_labels: z.array(z.string()).default([]),
    snippet_length: z.number().min(100).max(5000).default(1000),

    // Write Permissions
    mark_read: z.boolean().default(false),
    archive: z.boolean().default(false),
    apply_label: z.string().default(''),
    auto_tasking: z.boolean().default(false),
    task_list: z.string().default('@default'),
    reply_enabled: z.boolean().default(false),
    reply_mode: z.enum(['draft', 'send']).default('draft'),
    forward_to: z.string().default(''),
    calendar_aware: z.boolean().default(false),

    // Cost & Performance
    max_budget_per_run_usd: z.number().default(0.25),
    batch_size: z.number().min(1).max(50).default(20),
    run_window_start: z.string().default(''),
    run_window_end: z.string().default(''),

    // Notifications
    notify_channel: z.enum(['dashboard', 'imessage', 'telegram', 'none']).default('dashboard'),
    notify_on: z.enum(['always', 'matches_only', 'errors_only']).default('matches_only'),

    // Privacy
    privacy_keywords: z.array(z.string()).default([]),
  }).default({}),
  auto_update: z.object({
    enabled: z.boolean().default(true),
    check_interval_hours: z.number().min(1).max(24).default(1),
    install_hour: z.number().min(0).max(23).default(1),
  }).default({}),
  acknowledgment: z.object({
    enabled: z.boolean().default(true),
    style: z.enum(['pool', 'static', 'none']).default('pool'),
    static_message: z.string().default('Received, thinking...'),
    excluded_channels: z.array(z.string()).default(['dashboard']),
  }).default({}),
  memory: z.object({
    short_term_buffer_size: z.number().default(50),
    flush_interval_seconds: z.number().default(30),
    semantic_search_limit: z.number().default(5),
    knowledge_search_limit: z.number().default(5),
    max_context_tokens: z.number().default(4000),
  }).default({}),
  logging: z.object({
    level: z.string().default('info'),
    file: z.string().default('~/.murph/murph.log'),
  }).default({}),
});
